### ISSUE TITLE
BUG: eeg import error when running cmpbidsappmanager (cmp v.3.0.3)

### ISSUE THREAD

**Issue by MeropGont** [connectomicslab/connectomemapper3#150]
Hi,

I followed the installation instructions of cmp v3.0.3 step by step. Everything went well with creating the environment, installing the dependencies and the connectomemapper itself. But then when I want to run the GUI I get the following error which I'm guessing is related to implementing the new EEG pipeline.

OS: Ubuntu 20.04.4 LTS

(py37cmp-gui) fateme@fateme-HP:~$ cmpbidsappmanager
```
Traceback` (most recent call last):
  File "/home/fateme/miniconda3/envs/py37cmp-gui/bin/cmpbidsappmanager", line 5, in <module>
    from cmp.cli.cmpbidsappmanager import main
  File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/cli/cmpbidsappmanager.py", line 21, in <module>
    import cmp.bidsappmanager.gui.principal
  File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/bidsappmanager/gui/principal.py", line 21, in <module>
    import cmp.project
  File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/project.py", line 25, in <module>
    from cmp.pipelines.functional import eeg as EEG_pipeline
  File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/pipelines/functional/eeg.py", line 17, in <module>
    from cmp.stages.eeg.inverse_solution import EEGInverseSolutionStage
ModuleNotFoundError: No module named 'cmp.stages.eeg'

```

Best,
Fatemeh

**Comment by sebastientourbier** [comment]
Dear @MeropGont,

Thank you for reporting this issue.

Indeed, CMP3 is using two different setup.py files:
- https://github.com/connectomicslab/connectomemapper3/blob/master/setup.py installs CMP3 with all data resources (such as atlas images). It is used during development and for installing CMP3 in the BIDS App (docker image).
- https://github.com/connectomicslab/connectomemapper3/blob/master/setup_pypi.py is a lightweight installation of CMP3 (no data resources) that allows us to make python package < 100MB, the limit on the Python Index Package manager (pip). It is used to create and publish the package to pip.
So, following the guidelines, you should have used the package available in pip. 

While inspecting https://github.com/connectomicslab/connectomemapper3/blob/master/setup_pypi.py, I indeed did found that `cmp.stages.eeg` was missing in the package list to be installed. This will be fixed in the next release.

However, I still see a solution in the meantime!
You can use [setup.py](https://github.com/connectomicslab/connectomemapper3/blob/master/setup.py) that list all packages properly. This can be done with a single command as follows:
```bash
$ pip install git+https://github.com/connectomicslab/connectomemapper3.git@v3.0.3
```
Then, `cmpbidsappmanager` should start without any problem.

Let me know if that works!

Best,
Seb

**Comment by MeropGont** [comment]
Dear @sebastientourbier ,

many thanks for the clarification and the suggestion!
I ran the line of code per your instruction, and it seemed that setup.py was used this time, but unfortunately it didn't work. Meaning that it didn't install any new packages, and I still get the exact same error when I run cmpbidsappmanager. 

Here's the log:

```
(py37cmp-gui) fateme@fateme-HP:~$ pip install git+https://github.com/connectomicslab/connectomemapper3.git@v3.0.3
Collecting git+https://github.com/connectomicslab/connectomemapper3.git@v3.0.3
  Cloning https://github.com/connectomicslab/connectomemapper3.git (to revision v3.0.3) to /tmp/pip-req-build-coq1bmq_
  Running command git clone --filter=blob:none -q https://github.com/connectomicslab/connectomemapper3.git /tmp/pip-req-build-coq1bmq_
  Running command git checkout -q 9a74f0ac47307d4badff80968e2d2725d70ce789
  Resolved https://github.com/connectomicslab/connectomemapper3.git to commit 9a74f0ac47307d4badff80968e2d2725d70ce789
  Preparing metadata (setup.py) ... done
Requirement already satisfied: codecarbon==1.2.0 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from connectomemapper==3.0.3) (1.2.0)
Requirement already satisfied: dash-bootstrap-components==0.13.1 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from connectomemapper==3.0.3) (0.13.1)
Requirement already satisfied: APScheduler in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from codecarbon==1.2.0->connectomemapper==3.0.3) (3.9.1)
Requirement already satisfied: fire in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from codecarbon==1.2.0->connectomemapper==3.0.3) (0.4.0)
Requirement already satisfied: py-cpuinfo in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from codecarbon==1.2.0->connectomemapper==3.0.3) (8.0.0)
Requirement already satisfied: pynvml in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from codecarbon==1.2.0->connectomemapper==3.0.3) (11.4.1)
Requirement already satisfied: requests in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from codecarbon==1.2.0->connectomemapper==3.0.3) (2.27.1)
Requirement already satisfied: dash in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from codecarbon==1.2.0->connectomemapper==3.0.3) (2.3.1)
Requirement already satisfied: pandas in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from codecarbon==1.2.0->connectomemapper==3.0.3) (1.3.5)
Requirement already satisfied: Flask>=1.0.4 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from dash->codecarbon==1.2.0->connectomemapper==3.0.3) (2.1.1)
Requirement already satisfied: plotly>=5.0.0 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from dash->codecarbon==1.2.0->connectomemapper==3.0.3) (5.6.0)
Requirement already satisfied: dash-html-components==2.0.0 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from dash->codecarbon==1.2.0->connectomemapper==3.0.3) (2.0.0)
Requirement already satisfied: dash-table==5.0.0 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from dash->codecarbon==1.2.0->connectomemapper==3.0.3) (5.0.0)
Requirement already satisfied: dash-core-components==2.0.0 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from dash->codecarbon==1.2.0->connectomemapper==3.0.3) (2.0.0)
Requirement already satisfied: flask-compress in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from dash->codecarbon==1.2.0->connectomemapper==3.0.3) (1.11)
Requirement already satisfied: six>=1.4.0 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from APScheduler->codecarbon==1.2.0->connectomemapper==3.0.3) (1.16.0)
Requirement already satisfied: tzlocal!=3.*,>=2.0 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from APScheduler->codecarbon==1.2.0->connectomemapper==3.0.3) (4.2)
Requirement already satisfied: pytz in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from APScheduler->codecarbon==1.2.0->connectomemapper==3.0.3) (2022.1)
Requirement already satisfied: setuptools>=0.7 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from APScheduler->codecarbon==1.2.0->connectomemapper==3.0.3) (59.8.0)
Requirement already satisfied: termcolor in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from fire->codecarbon==1.2.0->connectomemapper==3.0.3) (1.1.0)
Requirement already satisfied: python-dateutil>=2.7.3 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from pandas->codecarbon==1.2.0->connectomemapper==3.0.3) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from pandas->codecarbon==1.2.0->connectomemapper==3.0.3) (1.21.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from requests->codecarbon==1.2.0->connectomemapper==3.0.3) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from requests->codecarbon==1.2.0->connectomemapper==3.0.3) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from requests->codecarbon==1.2.0->connectomemapper==3.0.3) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from requests->codecarbon==1.2.0->connectomemapper==3.0.3) (3.3)
Requirement already satisfied: Jinja2>=3.0 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from Flask>=1.0.4->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (3.1.1)
Requirement already satisfied: itsdangerous>=2.0 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from Flask>=1.0.4->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (2.1.2)
Requirement already satisfied: Werkzeug>=2.0 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from Flask>=1.0.4->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (2.1.1)
Requirement already satisfied: importlib-metadata>=3.6.0 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from Flask>=1.0.4->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (4.11.3)
Requirement already satisfied: click>=8.0 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from Flask>=1.0.4->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (8.1.2)
Requirement already satisfied: tenacity>=6.2.0 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from plotly>=5.0.0->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (8.0.1)
Requirement already satisfied: pytz-deprecation-shim in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from tzlocal!=3.*,>=2.0->APScheduler->codecarbon==1.2.0->connectomemapper==3.0.3) (0.1.0.post0)
Requirement already satisfied: backports.zoneinfo in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from tzlocal!=3.*,>=2.0->APScheduler->codecarbon==1.2.0->connectomemapper==3.0.3) (0.2.1)
Requirement already satisfied: brotli in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from flask-compress->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (1.0.9)
Requirement already satisfied: typing-extensions>=3.6.4 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from importlib-metadata>=3.6.0->Flask>=1.0.4->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (4.1.1)
Requirement already satisfied: zipp>=0.5 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from importlib-metadata>=3.6.0->Flask>=1.0.4->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (3.8.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from Jinja2>=3.0->Flask>=1.0.4->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (2.1.1)
Requirement already satisfied: tzdata in ./miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from pytz-deprecation-shim->tzlocal!=3.*,>=2.0->APScheduler->codecarbon==1.2.0->connectomemapper==3.0.3) (2022.1)

```
and when I run cmpbidsappmanager

```

(py37cmp-gui) fateme@fateme-HP:~/Desktop/CMP3$ cmpbidsappmanager
Traceback (most recent call last):
  File "/home/fateme/miniconda3/envs/py37cmp-gui/bin/cmpbidsappmanager", line 5, in <module>
    from cmp.cli.cmpbidsappmanager import main
  File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/cli/cmpbidsappmanager.py", line 21, in <module>
    import cmp.bidsappmanager.gui.principal
  File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/bidsappmanager/gui/principal.py", line 21, in <module>
    import cmp.project
  File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/project.py", line 25, in <module>
    from cmp.pipelines.functional import eeg as EEG_pipeline
  File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/pipelines/functional/eeg.py", line 17, in <module>
    from cmp.stages.eeg.inverse_solution import EEGInverseSolutionStage
ModuleNotFoundError: No module named 'cmp.stages.eeg'

```

I don't know if it helps in any way, but when I checked my list of site-packages, none of the cmp subsidiary packages that are listed in setup.py have been installed, I only have cmp itself. I'm attaching the list.

[package-list.txt](https://github.com/connectomicslab/connectomemapper3/files/8424947/package-list.txt)
.

Best,
Fatemeh

**Comment by sebastientourbier** [comment]
I am suspecting the version to not be updated and so the installed `/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp` is still missing `stages/eeg` folders.

Uninstalling and reinstalling as above should make the trick. Please find below the commands and outputs I obtained on my side:
```bash
$ pip uninstall connectomemapper
```
```output
Found existing installation: connectomemapper 3.0.3
Uninstalling connectomemapper-3.0.3:
  Would remove:
    /Applications/miniconda3/envs/py37cmp-gui/bin/cmpbidsappmanager
    /Applications/miniconda3/envs/py37cmp-gui/bin/connectomemapper3
    /Applications/miniconda3/envs/py37cmp-gui/bin/connectomemapper3_docker
    /Applications/miniconda3/envs/py37cmp-gui/bin/connectomemapper3_singularity
    /Applications/miniconda3/envs/py37cmp-gui/bin/showmatrix_gpickle
    /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/*
    /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmtklib/*
    /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/connectomemapper-3.0.3.dist-info/*
    /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/resources/*
Proceed (Y/n)? Y
  Successfully uninstalled connectomemapper-3.0.3
```

```bash
$ pip install git+https://github.com/connectomicslab/connectomemapper3.git@v3.0.3
```
```output
Collecting git+https://github.com/connectomicslab/connectomemapper3.git@v3.0.3
  Cloning https://github.com/connectomicslab/connectomemapper3.git (to revision v3.0.3) to /private/var/folders/vy/0bw_1jvj54n8lvcgvdrtqb0c0000gn/T/pip-req-build-1mkzidrb
  Running command git clone --filter=blob:none -q https://github.com/connectomicslab/connectomemapper3.git /private/var/folders/vy/0bw_1jvj54n8lvcgvdrtqb0c0000gn/T/pip-req-build-1mkzidrb
  warning: the following paths have collided (e.g. case-sensitive paths
  on a case-insensitive filesystem) and only one from the same
  colliding group is in the working tree:

    'docs/images/registration_FS.png'
    'docs/images/registration_fs.png'
  Running command git checkout -q 9a74f0ac47307d4badff80968e2d2725d70ce789
  Resolved https://github.com/connectomicslab/connectomemapper3.git to commit 9a74f0ac47307d4badff80968e2d2725d70ce789
  Preparing metadata (setup.py) ... done
Requirement already satisfied: codecarbon==1.2.0 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from connectomemapper==3.0.3) (1.2.0)
Requirement already satisfied: dash-bootstrap-components==0.13.1 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from connectomemapper==3.0.3) (0.13.1)
Requirement already satisfied: py-cpuinfo in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from codecarbon==1.2.0->connectomemapper==3.0.3) (8.0.0)
Requirement already satisfied: pandas in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from codecarbon==1.2.0->connectomemapper==3.0.3) (1.3.5)
Requirement already satisfied: APScheduler in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from codecarbon==1.2.0->connectomemapper==3.0.3) (3.8.1)
Requirement already satisfied: pynvml in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from codecarbon==1.2.0->connectomemapper==3.0.3) (11.4.1)
Requirement already satisfied: requests in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from codecarbon==1.2.0->connectomemapper==3.0.3) (2.27.1)
Requirement already satisfied: fire in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from codecarbon==1.2.0->connectomemapper==3.0.3) (0.4.0)
Requirement already satisfied: dash in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from codecarbon==1.2.0->connectomemapper==3.0.3) (2.1.0)
Requirement already satisfied: dash-core-components==2.0.0 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from dash->codecarbon==1.2.0->connectomemapper==3.0.3) (2.0.0)
Requirement already satisfied: dash-html-components==2.0.0 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from dash->codecarbon==1.2.0->connectomemapper==3.0.3) (2.0.0)
Requirement already satisfied: plotly>=5.0.0 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from dash->codecarbon==1.2.0->connectomemapper==3.0.3) (5.5.0)
Requirement already satisfied: flask-compress in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from dash->codecarbon==1.2.0->connectomemapper==3.0.3) (1.10.1)
Requirement already satisfied: dash-table==5.0.0 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from dash->codecarbon==1.2.0->connectomemapper==3.0.3) (5.0.0)
Requirement already satisfied: Flask>=1.0.4 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from dash->codecarbon==1.2.0->connectomemapper==3.0.3) (2.0.2)
Requirement already satisfied: pytz in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from APScheduler->codecarbon==1.2.0->connectomemapper==3.0.3) (2021.3)
Requirement already satisfied: setuptools>=0.7 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from APScheduler->codecarbon==1.2.0->connectomemapper==3.0.3) (59.8.0)
Requirement already satisfied: tzlocal!=3.*,>=2.0 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from APScheduler->codecarbon==1.2.0->connectomemapper==3.0.3) (4.1)
Requirement already satisfied: six>=1.4.0 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from APScheduler->codecarbon==1.2.0->connectomemapper==3.0.3) (1.16.0)
Requirement already satisfied: termcolor in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from fire->codecarbon==1.2.0->connectomemapper==3.0.3) (1.1.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from pandas->codecarbon==1.2.0->connectomemapper==3.0.3) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from pandas->codecarbon==1.2.0->connectomemapper==3.0.3) (1.21.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from requests->codecarbon==1.2.0->connectomemapper==3.0.3) (1.26.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from requests->codecarbon==1.2.0->connectomemapper==3.0.3) (2.0.11)
Requirement already satisfied: certifi>=2017.4.17 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from requests->codecarbon==1.2.0->connectomemapper==3.0.3) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from requests->codecarbon==1.2.0->connectomemapper==3.0.3) (3.3)
Requirement already satisfied: itsdangerous>=2.0 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from Flask>=1.0.4->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (2.0.1)
Requirement already satisfied: Werkzeug>=2.0 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from Flask>=1.0.4->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (2.0.2)
Requirement already satisfied: click>=7.1.2 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from Flask>=1.0.4->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (8.0.3)
Requirement already satisfied: Jinja2>=3.0 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from Flask>=1.0.4->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (3.0.3)
Requirement already satisfied: tenacity>=6.2.0 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from plotly>=5.0.0->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (8.0.1)
Requirement already satisfied: backports.zoneinfo in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from tzlocal!=3.*,>=2.0->APScheduler->codecarbon==1.2.0->connectomemapper==3.0.3) (0.2.1)
Requirement already satisfied: pytz-deprecation-shim in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from tzlocal!=3.*,>=2.0->APScheduler->codecarbon==1.2.0->connectomemapper==3.0.3) (0.1.0.post0)
Requirement already satisfied: brotli in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from flask-compress->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (1.0.9)
Requirement already satisfied: importlib-metadata in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from click>=7.1.2->Flask>=1.0.4->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (4.10.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from Jinja2>=3.0->Flask>=1.0.4->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (2.0.1)
Requirement already satisfied: tzdata in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from pytz-deprecation-shim->tzlocal!=3.*,>=2.0->APScheduler->codecarbon==1.2.0->connectomemapper==3.0.3) (2021.5)
Requirement already satisfied: typing-extensions>=3.6.4 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from importlib-metadata->click>=7.1.2->Flask>=1.0.4->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (4.0.1)
Requirement already satisfied: zipp>=0.5 in /Applications/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages (from importlib-metadata->click>=7.1.2->Flask>=1.0.4->dash->codecarbon==1.2.0->connectomemapper==3.0.3) (3.7.0)
Building wheels for collected packages: connectomemapper
  Building wheel for connectomemapper (setup.py) ... done
  Created wheel for connectomemapper: filename=connectomemapper-3.0.3-py3-none-any.whl size=240215555 sha256=adada77ebc73521915affd1380a062dfc3497be4f8cc0f698c5a96ebaa816e50
  Stored in directory: /private/var/folders/vy/0bw_1jvj54n8lvcgvdrtqb0c0000gn/T/pip-ephem-wheel-cache-drwyyww9/wheels/ca/9e/8c/373c0b375f9c955d49ba8e82d55557edfb6607a4c24d1fc1a0
Successfully built connectomemapper
Installing collected packages: connectomemapper
Successfully installed connectomemapper-3.0.3
```

And then, the GUI seems to load without any error on my side:
```
$ cmpbidsappmanager                                                              

Connectome Mapper v3.0.3 - BIDS App Manager 
------------------------------------------------------
Copyright (C) 2009-2022, Ecole Polytechnique Federale de Lausanne (EPFL) the University Hospital Center and University of Lausanne (UNIL-CHUV), Switzerland, and Contributors, All rights reserved.
------------------------------------------------------
------------------------------------------------------
  .. INFO: Use qt for graphical backend
------------------------------------------------------

```

**Comment by MeropGont** [comment]
It worked! Thanks so much.
