### ISSUE TITLE
error when starting cmpbidsappmanager

### ISSUE THREAD

**Issue by JuergenHaenggi** [connectomicslab/connectomemapper3#225]
Dear connectomemapper3 experts

I installed the connectome mapper 3 bids app and its manager on a Mac as described on you website. Then I tried to start the manager but the following error occurred:

(py39cmp-gui) [upddkp224:~] jurgenhanggi% cmpbidsappmanager
Traceback (most recent call last):
  File "/Users/jurgenhanggi/miniconda3/envs/py39cmp-gui/bin/cmpbidsappmanager", line 5, in <module>
    from cmp.cli.cmpbidsappmanager import main
  File "/Users/jurgenhanggi/miniconda3/envs/py39cmp-gui/lib/python3.9/site-packages/cmp/cli/cmpbidsappmanager.py", line 30, in <module>
    import cmp.bidsappmanager.gui.principal
  File "/Users/jurgenhanggi/miniconda3/envs/py39cmp-gui/lib/python3.9/site-packages/cmp/bidsappmanager/gui/principal.py", line 28, in <module>
    import cmp.bidsappmanager.gui.config
  File "/Users/jurgenhanggi/miniconda3/envs/py39cmp-gui/lib/python3.9/site-packages/cmp/bidsappmanager/gui/config.py", line 26, in <module>
    import cmp.bidsappmanager.project as project
  File "/Users/jurgenhanggi/miniconda3/envs/py39cmp-gui/lib/python3.9/site-packages/cmp/bidsappmanager/project.py", line 48, in <module>
    from cmp.bidsappmanager.pipelines.anatomical import anatomical as anatomical_pipeline
  File "/Users/jurgenhanggi/miniconda3/envs/py39cmp-gui/lib/python3.9/site-packages/cmp/bidsappmanager/pipelines/anatomical/anatomical.py", line 16, in <module>
    from pyface.ui.qt4.image_resource import ImageResource
ModuleNotFoundError: No module named 'pyface.ui.qt4.image_resource'

Any idea how to solve this problem is highly appreciated.
Thanks in advance
Best regards
Jürgen

**Comment by emullier** [comment]
Hi Jurgen,

Did you solve the issue?
Can you check which version of pyface you are using with 'pip show pyface'?

Regards,

Emeline

**Comment by JuergenHaenggi** [comment]
Dear Emeline

Thanks for your response. I did not solve the issue yet.
I am working on a Mac and when running “pip show pyface” the command pip is not found.
Maybe I must install pip on the Mac.
However, pyface seems to be installed as part of FSL (in several locations) and also as part of miniconda3/envs/py39cmp-gui/lib/python3.9/site-packages/pyface.

Regards,
Jürgen

Von: Emeline Mullier ***@***.***>
Datum: Donnerstag, 19. Oktober 2023 um 16:30
An: connectomicslab/connectomemapper3 ***@***.***>
Cc: Hänggi, Jürgen (UPD) ***@***.***>, Author ***@***.***>
Betreff: Re: [connectomicslab/connectomemapper3] error when starting cmpbidsappmanager (Issue #225)
Sie erhalten nicht oft eine E-Mail von ***@***.*** Erfahren Sie, warum dies wichtig ist<https://aka.ms/LearnAboutSenderIdentification>

Hi Jurgen,

Did you solve the issue?
Can you check which version of pyface you are using with 'pip show pyface'?

Regards,

Emeline
