### ISSUE TITLE
Same error in both docker, singularity, and gui

### ISSUE THREAD

**Issue by iPsych** [connectomicslab/connectomemapper3#239]
Same error in both docker, singularity, and gui
with below log in sub-001_log.txt 
nothing happened, and all the processes finished.

`> Looking in /bids_dir for....
--- Set Freesurfer and ANTs to use 1 threads by the means of OpenMP
ERROR : Invalid inputs for anatomical pipeline
Traceback (most recent call last):
  File "/opt/conda/envs/py38cmp-core/bin/connectomemapper3", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/py38cmp-core/lib/python3.8/site-packages/cmp/cli/connectomemapper3.py", line 192, in main
    exit_code = cmp.project.run_individual(
  File "/opt/conda/envs/py38cmp-core/lib/python3.8/site-packages/cmp/project.py", line 1047, in run_individual
    _, exit_code, _, _ = run_anat_pipeline(project, bids_layout, number_of_threads)
  File "/opt/conda/envs/py38cmp-core/lib/python3.8/site-packages/cmp/project.py", line 1140, in run_anat_pipeline
    return anat_pipeline, exit_code, anat_valid_outputs, msg
UnboundLocalError: local variable 'anat_valid_outputs' referenced before assignment`

**Comment by iPsych** [comment]
Finished the homework myself, after read lines in anatomical.py.

Even your data passed BIDS-validator,
current version (3.2) of connectomemapper requires .nii.gz (not .nii) for T1 image, and T1w (not t1w, case sensitive).
