### ISSUE TITLE
MemoryError raised by ParcThal when run on CircleCI 

### ISSUE THREAD

**Issue by sebastientourbier** [connectomicslab/connectomemapper3#30]
Continuous integration testing with CIrcleCI failed when parcellating the thalamic nuclei with a Memory error message (see [execution log on circleCI page](https://270-183162514-gh.circle-artifacts.com/0/tmp/data/ds-sample/derivatives/cmp/sub-01_ses-01_log.txt) more details). Seems 7.5GB RAM is not enough to handle `ind = np.where(Ispams < Thresh)`. See error message below:
**Error**
```
200317-16:44:09,131 nipype.interface INFO:
	 Correcting the volumes after the interpolation 
Save output image to /output_dir/nipype/sub-01/ses-01/anatomical_pipeline/parcellation_stage/parcThal/T1_class-thalamus_dtissue_after_ants.nii.gz
200317-16:45:11,524 nipype.workflow WARNING:
	 [Node] Error on "anatomical_pipeline.parcellation_stage.parcThal" (/output_dir/nipype/sub-01/ses-01/anatomical_pipeline/parcellation_stage/parcThal)
200317-16:45:11,545 nipype.workflow ERROR:
	 Node parcThal failed to run on host 3be4adbaba2e.
200317-16:45:11,690 nipype.workflow ERROR:
	 Saving crash info to /tmp/crash-20200317-164511-root-parcThal-2682b8cb-8991-437c-977c-d15ba5964b8e.txt
Traceback (most recent call last):
  File "/opt/conda/envs/py27cmp-core/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 48, in run
    node.run(updatehash=updatehash)
  File "/opt/conda/envs/py27cmp-core/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/py27cmp-core/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 557, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/py27cmp-core/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 637, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/envs/py27cmp-core/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 369, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/envs/py27cmp-core/lib/python2.7/site-packages/cmtklib/parcellation.py", line 1364, in _run_interface
    ind = np.where(Ispams < Thresh)
MemoryError
```
**System configuration on CircleCI**
Machine Linux Medium
2 CPU / 7.5 GB RAM

**Comment by sebastientourbier** [comment]
Fixed by Commit dbae66d09930e6e02eb47c33bcd2f1680de982a7 in pull request #28
