### ISSUE TITLE
Problems while setting up the conda environment/ cannot find libffi

### ISSUE THREAD

**Issue by davidose** [connectomicslab/connectomemapper3#35]
Hello, 

I have been trying to install the Connectome mapper, but I am getting an error message while setting up the conda environment:

```
(base) Davids-MBP-3:Applications mynotebook$ conda env create -f connectomemapper3/environment.yml
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Ran pip subprocess with arguments:
[u'/opt/miniconda2/envs/py27cmp-gui/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Applications/connectomemapper3/tmp2JfN7s.requirements.txt']
Pip subprocess output:

Pip subprocess error:
Traceback (most recent call last):
  File "/opt/miniconda2/envs/py27cmp-gui/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/miniconda2/envs/py27cmp-gui/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/miniconda2/envs/py27cmp-gui/lib/python2.7/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal import main as _main  # isort:skip # noqa
  File "/opt/miniconda2/envs/py27cmp-gui/lib/python2.7/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/opt/miniconda2/envs/py27cmp-gui/lib/python2.7/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/opt/miniconda2/envs/py27cmp-gui/lib/python2.7/site-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "/opt/miniconda2/envs/py27cmp-gui/lib/python2.7/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/opt/miniconda2/envs/py27cmp-gui/lib/python2.7/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/opt/miniconda2/envs/py27cmp-gui/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 20, in <module>
    from pip._internal.download import PipSession
  File "/opt/miniconda2/envs/py27cmp-gui/lib/python2.7/site-packages/pip/_internal/download.py", line 37, in <module>
    from pip._internal.utils.glibc import libc_ver
  File "/opt/miniconda2/envs/py27cmp-gui/lib/python2.7/site-packages/pip/_internal/utils/glibc.py", line 3, in <module>
    import ctypes
  File "/opt/miniconda2/envs/py27cmp-gui/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/opt/miniconda2/envs/py27cmp-gui/lib/python2.7/lib-dynload/_ctypes.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /opt/miniconda2/envs/py27cmp-gui/lib/python2.7/lib-dynload/_ctypes.so
  Reason: image not found

CondaEnvException: Pip failed
```

I have already tried reinstalling libffi with homebrew and renaming the libffi.7.dylib file to libffi.6.dylib in my conda environment and in /usr/local, however it seems that the program cannot find the libffi.6.dylib file. 

Has anyone any ideas how to fix this issue?

Thanks in advance,
David

**Comment by ajbarn** [comment]
I am having the same issue. I tried completely uninstalling and reinstalling anaconda and that also failed to fix the issue.

I hope that a solution can be found,

Alex

**Comment by sebastientourbier** [comment]
Sorry, I did not managed to get your issue until now but I found this conda issue:
https://github.com/conda/conda/issues/9038

Have you tried under /opt/miniconda2/lib to create a symbolink link:
```
ln -s libffi.7.dylib libffi.6.dylib
```
?

**Comment by ajbarn** [comment]
I tried

`
ln -s libffi.7.dylib libffi.6.dylib
`
in the /opt/miniconda2/lib directory as well as in the /opt/anaconda3/lib directory
but neither resolved the problem.

**Comment by sebastientourbier** [comment]
Ok thank you.
Just please could you give me more information about your environment?

You can get conda info by:
```
$ conda info
```

You can get cmp version by running:
```
$ python /path/to/connectomemapper3/get_version.py
```

Also could you indicate me the operating system and version you are using?

All this information would be very useful in order to reproduce the error and find a solution. All any other details that would be of help are also welcome.

In the meantime, have you tried to create the conda environment manually i.e.:
```
$conda create --name py27cmp-gui python=2.7.15
$conda activate py27cmp-gui
( py27cmp-gui)$conda config --add channels aramislab
( py27cmp-gui)$conda config --add channels anaconda
( py27cmp-gui)$conda config --add channels conda-forge
( py27cmp-gui)$conda config --add channels defaults
( py27cmp-gui)$conda install pip=19.0.3
( py27cmp-gui)$conda install numpy=1.15.4
( py27cmp-gui)$conda install matplotlib=2.2.3
( py27cmp-gui)$conda install traits=5.1
( py27cmp-gui)$conda install traitsui=6.0.0
( py27cmp-gui)$conda install graphviz=2.40.1
( py27cmp-gui)$conda install nipype=1.1.8
( py27cmp-gui)$conda install git-annex=7.20190219
( py27cmp-gui)$conda install pyside2=5.9.0a1
( py27cmp-gui)$pip install git+https://github.com/LTS5/cfflib.git
( py27cmp-gui)$pip install duecredit==0.7.0
( py27cmp-gui)$pip install dipy==0.15.0
( py27cmp-gui)$pip install mne==0.17.1
( py27cmp-gui)$pip install obspy==1.1.1
( py27cmp-gui)$pip install datalad[full]==0.11.4
( py27cmp-gui)$pip install datalad-revolution==0.6.0
( py27cmp-gui)$pip install datalad-container==0.3.1
( py27cmp-gui)$pip install datalad_neuroimaging==0.2.0
( py27cmp-gui)$pip install pybids==0.9.1
( py27cmp-gui)$pip install apptools==4.4.0
( py27cmp-gui)$pip install statsmodels==0.9.0
( py27cmp-gui)$pip install networkx==2.2
( py27cmp-gui)$pip install sphinx==1.8.5
( py27cmp-gui)$pip install sphinx_rtd_theme==0.4.3
( py27cmp-gui)$pip install sphinx-argparse==0.2.5
( py27cmp-gui)$pip install recommonmark==0.5.0
```

**Comment by ajbarn** [comment]
```
$ conda info

active environment : base
active env location : /Users/alexbarnett/opt/anaconda3
shell level : 2
user config file : /Users/alexbarnett/.condarc
populated config files : /Users/alexbarnett/.condarc
conda version : 4.8.2
conda-build version : 3.18.11
python version : 3.7.6.final.0
virtual packages : __osx=10.13.6
base environment : /Users/alexbarnett/opt/anaconda3  (writable)
channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
https://repo.anaconda.com/pkgs/main/noarch
https://repo.anaconda.com/pkgs/r/osx-64
https://repo.anaconda.com/pkgs/r/noarch
package cache : /Users/alexbarnett/opt/anaconda3/pkgs
/Users/alexbarnett/.conda/pkgs
envs directories : /Users/alexbarnett/opt/anaconda3/envs
/Users/alexbarnett/.conda/envs
platform : osx-64
user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Darwin/17.7.0 OSX/10.13.6
UID:GID : 501:20
netrc file : None
offline mode : False
```

```
$ python connectomemapper3/get_version.py 
v3.0.0-beta-RC1
```
operating system: MacOS High Sierra 10.13.6


I am currently trying the manual environment set up but got stuck on 

```
$ conda install git-annex=7.20190219
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - git-annex=7.20190219

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/anaconda/osx-64
  - https://conda.anaconda.org/anaconda/noarch
  - https://conda.anaconda.org/aramislab/osx-64
  - https://conda.anaconda.org/aramislab/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

However, I continued installing the other packages and it seems that I can successfully run the install and open the `cmpbidsappmanager`

**Comment by sebastientourbier** [comment]
Ok great.
Indeed conda package `git-annex=7.20190219` does not exist on MacOSX. 
It has to be installed using homebrew but it is not necessary (see https://github.com/connectomicslab/connectomemapper3/issues/32#issuecomment-608529661)
