### ISSUE TITLE
DTI Reconstruction & Tractography settings will not open

### ISSUE THREAD

**Issue by smeisler** [connectomicslab/connectomemapper3#46]
Hi dev team,

Really excited to try this tool out! I happened to find this just as I began a bimodal connectivity study. I installed the BIDS-app docker container and GUI python code, and I was met with the following error upon trying to enter the DTI Reconstruction and Tractography Settings:

```
Exception occurred in traits notification handler for object: <cmp.bidsappmanager.pipelines.diffusion.diffusion.DiffusionPipelineUI object at 0x2b3bdca059b0>, trait: diffusion, old value: <undefined>, new value: 0
Traceback (most recent call last):
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traits/trait_notifiers.py", line 381, in __call__
    self.handler(*args)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/bidsappmanager/pipelines/diffusion/diffusion.py", line 116, in _diffusion_fired
    self.stages['Diffusion'].configure_traits(view=self.view_mode)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traits/has_traits.py", line 2088, in configure_traits
    args,
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/toolkit.py", line 224, in view_application
    id, scrollable, args)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/view_application.py", line 92, in view_application
    args=args)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/view.py", line 446, in ui
    ui.ui(parent, kind)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/ui.py", line 244, in ui
    self.rebuild(self, parent)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/toolkit.py", line 159, in ui_livemodal
    ui_live.ui_livemodal(ui, parent)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_live.py", line 47, in ui_livemodal
    _ui_dialog(ui, parent, BaseDialog.MODAL)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_live.py", line 63, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_base.py", line 278, in display_ui
    ui.owner.init(ui, parent, style)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_live.py", line 203, in init
    self.add_contents(panel(ui), bbox)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 265, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 603, in __init__
    layout = self._add_groups(content, inner)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 683, in _add_groups
    panel = _GroupPanel(subgroup, self.ui).control
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 605, in __init__
    layout = self._add_items(content, inner)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 876, in _add_items
    editor.prepare(inner)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/editor.py", line 172, in prepare
    self.update_editor()
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/instance_editor.py", line 303, in update_editor
    self.resynch_editor()
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/instance_editor.py", line 364, in resynch_editor
    self.factory.id)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/view.py", line 446, in ui
    ui.ui(parent, kind)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/ui.py", line 244, in ui
    self.rebuild(self, parent)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/toolkit.py", line 152, in ui_subpanel
    ui_panel.ui_subpanel(ui, parent)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 78, in ui_subpanel
    _ui_panel_for(ui, parent, True)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 84, in _ui_panel_for
    ui.control = control = _Panel(ui, parent, is_subpanel).control
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 148, in __init__
    self.control = panel(ui)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 265, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 603, in __init__
    layout = self._add_groups(content, inner)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 683, in _add_groups
    panel = _GroupPanel(subgroup, self.ui).control
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 605, in __init__
    layout = self._add_items(content, inner)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 876, in _add_items
    editor.prepare(inner)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/editor.py", line 172, in prepare
    self.update_editor()
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/instance_editor.py", line 303, in update_editor
    self.resynch_editor()
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/instance_editor.py", line 364, in resynch_editor
    self.factory.id)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/view.py", line 446, in ui
    ui.ui(parent, kind)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/ui.py", line 244, in ui
    self.rebuild(self, parent)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/toolkit.py", line 152, in ui_subpanel
    ui_panel.ui_subpanel(ui, parent)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 78, in ui_subpanel
    _ui_panel_for(ui, parent, True)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 84, in _ui_panel_for
    ui.control = control = _Panel(ui, parent, is_subpanel).control
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 148, in __init__
    self.control = panel(ui)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 265, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 603, in __init__
    layout = self._add_groups(content, inner)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 683, in _add_groups
    panel = _GroupPanel(subgroup, self.ui).control
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 605, in __init__
    layout = self._add_items(content, inner)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 868, in _add_items
    ui, object, name, item.tooltip, None
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/editor_factory.py", line 147, in simple_editor
    description=description)
  File "/om2/user/smeisler/anaconda3/envs/py37cmp-gui/lib/python3.7/site-packages/traitsui/editor.py", line 147, in __init__
    self.old_value = getattr(self.object, self.name)
AttributeError: 'Dipy_recon_configUI' object has no attribute 'shore_lambdaN'
```

I supposed I can edit these settings in the .ini / .json files directly, but it would be more convenient to do so in the GUI. 

Thanks in advance for the help!
Steven

**Comment by smeisler** [comment]
I spotted on the github summary page that there was a commit to update these variable names. I was able to change it manually on my end, but it was not distributed when I cloned the repo yesterday.

**Comment by sebastientourbier** [comment]
Thanks steven to report this. 
Which version of the connectomemapper do you use?

**Comment by smeisler** [comment]
This was with the current release v3.0.0-RC1. I think the fix is on the master branch but has not been distributed with a new release yet.

**Comment by sebastientourbier** [comment]
You are totally right!
