### ISSUE TITLE
FSL BET Error

### ISSUE THREAD

**Issue by smeisler** [connectomicslab/connectomemapper3#50]
Hi,

I came across the following error when using FSL from brain extraction:

```
Node: anatomical_pipeline.segmentation_stage.fsl_bet
Working directory: /output_dir/nipype/sub-ABCD1714/anatomical_pipeline/segmentation_stage/fsl_bet

Node inputs:

args = <undefined>
center = <undefined>
environ = {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
frac = <undefined>
functional = <undefined>
in_file = /output_dir/nipype/sub-ABCD1714/anatomical_pipeline/segmentation_stage/niigzConvert/nu.nii.gz
mask = True
mesh = <undefined>
no_output = <undefined>
out_file = brain.nii.gz
outline = <undefined>
output_type = NIFTI_GZ
padding = <undefined>
radius = <undefined>
reduce_bias = <undefined>
remove_eyes = <undefined>
robust = True
skull = True
surfaces = <undefined>
t2_guided = <undefined>
threshold = <undefined>
vertical_gradient = <undefined>

Traceback (most recent call last):
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/pipeline/plugins/linear.py", line 46, in run
    node.run(updatehash=updatehash)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/interfaces/fsl/preprocess.py", line 162, in _run_interface
    runtime = super(BET, self)._run_interface(runtime)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 792, in _run_interface
    self.raise_exception(runtime)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 723, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
bet /output_dir/nipype/sub-ABCD1714/anatomical_pipeline/segmentation_stage/niigzConvert/nu.nii.gz brain.nii.gz -m -R -s
Standard output:
/opt/fsl/bin/bet failed during operation
Standard error:
/opt/fsl/bin/bet: line 267: dc: command not found
Return code: 1
```

Freesurfer brain extraction seems to work okay, however.

Best,
Steven

**Comment by sebastientourbier** [comment]
Thanks a lot for reporting this! 
Seems "dc" is missing in the Docker image environment. This can be fix by installing it via apt-get:
```
$ (sudo) apt-get install dc
```
This should be fixed this in the new upcoming version (PR #45)
