### ISSUE TITLE
Node compute_matrice failed to run: empty graph as output

### ISSUE THREAD

**Issue by dualon** [connectomicslab/connectomemapper3#65]
Hi,

I am trying to create connectomes from in-house T1 and DTI data.
The pipeline throws an error at the connectome stage, see the attached log file from one dataset. I can provide the config files as well upon request, here I couldn't attach them.

I tried 2 independent datasets, one with a Lausanne2018 parcellation scheme without thalamic, hippocampal and brainstem parcellatin, the other one with Lausanne2008 parcellation. The expected output were in both cases scale 1-5 .graphml and .gpickle files.

A fix, or a hint/idea (in which direction I should look for the solution) would be much appreciated. I may try to fix the code myself if I get some instructions.

[sub-02_log.txt](https://github.com/connectomicslab/connectomemapper3/files/5889453/sub-02_log.txt)

Thanks in advance.

```python
... INFO - Found 22461 (6.973690 percent out of 322082 fibers) fibers that start or terminate in a voxel which is not labeled. (orphans)
  ... INFO - Valid fibers: 299621 (93.026310 percent)
  ************************************************
  >> Save connectome maps as :
    - connectome_scale1.tsv
    - connectome_scale1.gpickle
210128-17:39:33,59 nipype.workflow WARNING:
	 Storing result file without outputs
210128-17:39:33,59 nipype.workflow WARNING:
	 [Node] Error on "diffusion_pipeline.connectome_stage.compute_matrice" (/output_dir/nipype/sub-03/diffusion_pipeline/connectome_stage/compute_matrice)
210128-17:39:33,61 nipype.workflow ERROR:
	 Node compute_matrice failed to run on host 7ec47b578ff4.
210128-17:39:33,61 nipype.workflow ERROR:
	 Saving crash info to /tmp/crash-20210128-173933-UID1000-compute_matrice-18dd9f07-e254-43e3-b463-a6767a632256.txt
Traceback (most recent call last):
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/pipeline/plugins/linear.py", line 46, in run
    node.run(updatehash=updatehash)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/cmtklib/connectome.py", line 820, in _run_interface
    output_types=self.inputs.output_types)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/cmtklib/connectome.py", line 692, in cmat
    g2.node[u_gml]['dn_correspondence_id'] = d_gml['dn_correspondence_id']
AttributeError: 'Graph' object has no attribute 'node'

Traceback (most recent call last):
  File "/opt/conda/envs/py37cmp-core/bin/connectomemapper3", line 196, in <module>
    dmri_pipeline.process()
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/cmp/pipelines/diffusion/diffusion.py", line 1330, in process
    flow.run()
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 632, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/pipeline/plugins/linear.py", line 46, in run
    node.run(updatehash=updatehash)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/cmtklib/connectome.py", line 820, in _run_interface
    output_types=self.inputs.output_types)
  File "/opt/conda/envs/py37cmp-core/lib/python3.7/site-packages/cmtklib/connectome.py", line 692, in cmat
    g2.node[u_gml]['dn_correspondence_id'] = d_gml['dn_correspondence_id']
AttributeError: 'Graph' object has no attribute 'node'
```

Edit:
```
(base) dualon@alpha-neuron:/mnt/wdred1/Research/connectomemapper3$ docker images
REPOSITORY                                   TAG               IMAGE ID       CREATED         SIZE
sebastientourbier/connectomemapper-bidsapp   v3.0.0-RC2        e6a398ed8393   46 hours ago    17.8GB
sebastientourbier/connectomemapper-bidsapp   <none>            47e2a2a7bec0   4 weeks ago     17.8GB
hello-world                                  latest            bf756fb1ae65   13 months ago   13.3kB
ubuntu                                       xenial-20181218   b0ef3016420a   2 years ago     117MB

(py37cmp-gui) dualon@alpha-neuron:/mnt/wdred1/Research/connectomemapper3$ cat /proc/version
Linux version 5.8.0-40-generic (buildd@lcy01-amd64-013) (gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0, GNU ld (GNU Binutils for Ubuntu) 2.35.1) #45-Ubuntu SMP Fri Jan 15 11:05:36 UTC 2021
```

**Comment by sebastientourbier** [comment]
Hi @dualon!
Thanks for reporting this!
Actually it seems the code for saving connectome as graphml is still using the old networkx 1.X implementation (https://networkx.org/documentation/networkx-1.11/tutorial/tutorial.html#node-attributes) and has not not updated to networkx 2.X (https://networkx.org/documentation/stable/tutorial.html#node-attributes).
I'm currently making a hot-fix for this and will make a new v3.0.0-RC2-hotfix1 release. Let you know when it is done.
In the meantime, you could still save the connectomes as gpickle which is the networkx format and then convert them to graphml a posteriori, as the following:
```python
import networkx as nx
G = nx.read_gpickle('/path/to/connectome.gpickle')
nx.write_graphml(G, '/path/to/connectome.graphml')
```

**Comment by dualon** [comment]
Dear Sébastien,
Thanks a lot for the quick fix, I update the pipeline and run the data again.
Regarding the output: I am familiar with networkx, unfortunately there was no gpickle output at all. The GraphML outputs are also only labels. I will give you a feedback as soon as the updated pipeline has finished.

```
(base) dualon@alpha-neuron:~/BIDS-02/derivatives/cmp$ find sub-02/ -print
sub-02/
sub-02/sub-02_anatomical_config.ini
sub-02/sub-02_diffusion_config.ini
sub-02/sub-02_log.txt

sub-02/anat
sub-02/anat/sub-02_desc-brain_T1w.nii.gz
sub-02/anat/sub-02_label-L2018_desc-scale3_atlas_FreeSurferColorLUT.txt
sub-02/anat/sub-02_label-L2018_desc-scale4_stats.tsv
sub-02/anat/sub-02_label-L2018_desc-scale1_atlas.graphml
sub-02/anat/sub-02_desc-cmp_T1w.nii.gz
sub-02/anat/sub-02_label-L2018_desc-scale1_atlas.nii.gz
sub-02/anat/sub-02_desc-aseg_dseg.nii.gz
sub-02/anat/sub-02_label-L2018_desc-scale3_stats.tsv
sub-02/anat/sub-02_label-WM_desc-eroded_dseg.nii.gz
sub-02/anat/sub-02_label-L2018_desc-scale5_atlas.graphml
sub-02/anat/sub-02_label-L2018_desc-scale1_stats.tsv
sub-02/anat/sub-02_label-L2018_desc-scale5_stats.tsv
sub-02/anat/sub-02_label-L2018_desc-scale2_atlas.nii.gz
sub-02/anat/sub-02_label-L2018_desc-scale1_atlas_FreeSurferColorLUT.txt
sub-02/anat/sub-02_label-L2018_desc-scale4_atlas_FreeSurferColorLUT.txt
sub-02/anat/sub-02_desc-brain_mask.nii.gz
sub-02/anat/sub-02_label-L2018_desc-scale5_atlas_FreeSurferColorLUT.txt
sub-02/anat/sub-02_label-L2018_desc-scale2_atlas_FreeSurferColorLUT.txt
sub-02/anat/sub-02_label-L2018_desc-scale3_atlas.graphml
sub-02/anat/sub-02_label-GM_dseg.nii.gz
sub-02/anat/sub-02_label-WM_dseg.nii.gz
sub-02/anat/sub-02_label-CSF_desc-eroded_dseg.nii.gz
sub-02/anat/sub-02_desc-head_T1w.nii.gz
sub-02/anat/sub-02_label-brain_desc-eroded_dseg.nii.gz
sub-02/anat/sub-02_desc-aparcaseg_dseg.nii.gz
sub-02/anat/sub-02_label-L2018_desc-scale3_atlas.nii.gz
sub-02/anat/sub-02_label-L2018_desc-scale5_atlas.nii.gz
sub-02/anat/sub-02_label-CSF_dseg.nii.gz
sub-02/anat/sub-02_label-L2018_desc-scale4_atlas.graphml
sub-02/anat/sub-02_label-L2018_desc-scale2_atlas.graphml
sub-02/anat/sub-02_label-L2018_desc-scale2_stats.tsv
sub-02/anat/sub-02_label-L2018_desc-scale4_atlas.nii.gz

sub-02/dwi
sub-02/dwi/sub-02_desc-cmp_dwi.bvec
sub-02/dwi/sub-02_desc-cmp_dwi.bval
sub-02/dwi/sub-02_desc-cmp_dwi.nii.gz
```

**Comment by sebastientourbier** [comment]
Hi @dualon !

Please could you provide me with the configuration file for the diffusion pipeline ?

It seems one of the output format for connectome is graphml that makes the pipeline failing and so it never goes until the end and the different DWI derivatives (in `cmp/sub-02/dwi`) are not saved.

*Note:* The graphml files in `sub-02/anat` are indeed not the connectomes but the description of the different node for a given parcellation scale.

**Comment by sebastientourbier** [comment]
Also forgot to say but the docker image with hotfix has not been updated yet, waiting for the continuous integration testing to be completed.

**Comment by dualon** [comment]
Dear @sebastientourbier ,

The code/<config files> are here: [configs.zip](https://github.com/connectomicslab/connectomemapper3/files/5906436/configs.zip)
The derivatives/cmp/sub-02/<config files> are here: 
[sub-02-derivatives-config.zip](https://github.com/connectomicslab/connectomemapper3/files/5906476/sub-02-derivatives-config.zip)

The [above listed](https://github.com/connectomicslab/connectomemapper3/issues/65#issuecomment-770179240) directory tree shows the whole output. The connectomes, which I found in sub-02/dwi in earlier versions, are indeed missing.

Thanks for the fixes and for the update of the docker image, I'll keep an eye on it. Your effort is appreciated.

**Comment by sebastientourbier** [comment]
@dualon You're welcome!
So when looking at your `ref_diffusion_config.ini` and the subsequently created `sub-02_diffusion_config.ini` the format in graphml for connectome is still set:
```
[connectome_stage]
output_types = ['gPickle', 'graphml']
```
By changing this line in your `ref_diffusion_config.ini` to:
```
output_types = ['gPickle']
```
should allow you to make the whole connectome mapping successful.

**Comment by dualon** [comment]
That's great, I'll give it a try today.

**Comment by dualon** [comment]
Dear Sébastien @sebastientourbier ,
I can confirm that the RC2 pipeline finishes without GraphML out. Thanks for the support.
